export const MAP_API_KEY = 'AIzaSyCW5-dmdhctK0XdrHO7VmH7CoA3w4aj3w4';
export const FS_CLIENT_ID = 'ODQMNY5FDQMREIKMDWL1OZI2L52TLTRNVJX0HISD1Y5NLSAV';
export const FS_CLIENT_SECRET = 'TRPVEKGCJQUM3LALNDL4G0FIIIAUGVC4BP3IHZRBPB4CGBF0';
